export const ADD_STUDENT = Symbol('add_student')
export const DELETE_STUDENT = Symbol('delete_student')
export const UPDATE_STUDENT = Symbol('update_student')
export const SET_STUDENT = Symbol('set_student')
export const SET_ISLOADING = Symbol('set_isLoading')