export const ADD_NUM = Symbol('add_num')
export const DECREASE_NUM = Symbol('decrease_num')
export const SET_NUM = Symbol('set_num')
export const ASYNC_INCREASE_NUM = Symbol('async-increase-num')
export const ASYNC_DECREASE_NUM = Symbol('async-decrease-num')
